# Creds to https://github.com/docker/awesome-compose/blob/master/minecraft/compose.yaml

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes: 
      - ./minecraft_data:/data
    networks: 
      - mcnet
    restart: unless-stopped
    environment:
      EULA: "TRUE"                    
      TYPE: "PAPER"                   # PaperMc          
      MEMORY: "1.5G"                  # Is this enough?????               
      ENABLE_RCON: "true"             # Remote console access (should be false but leave for test)       
      RCON_PASSWORD: "admin"
    volumes:
      - ./minecraft_data:/data       
    deploy:
      resources:
        limits:
          memory: 1.5G                 # Limit container memory usage
