# Creds to https://github.com/docker/awesome-compose/blob/master/minecraft/compose.yaml

services:
  minecraft:
    build: .
    ports:
      - "25565:25565"
    volumes: 
      - ./minecraft_data:/data
    networks: 
      - mcnet
    restart: unless-stopped
    environment:
      EULA: "TRUE"                    
      TYPE: "PAPER"                   # PaperMc          
      MEMORY: "1.5G"                  # Is this enough?????               
      ENABLE_RCON: "true"             # Remote console access (should be false but leave for test)       
      RCON_PASSWORD: "admin"
    volumes:
      - ./minecraft_data:/data       
    deploy:
      resources:
        limits: 
          memory: "1.5G"
  db:
    image: mariadb
    container_name: mc-database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: minecraft
      MYSQL_USER: mcuser
      MYSQL_PASSWORD: mcpass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mcnet
    restart: unless-stopped
    
networks:
  mcnet:
    driver: bridge
volumes:
  db_data:

