apiVersion: v1
kind: Pod
metadata: 
  name: myapp-pod
  labels:
    env: development
spec:
  containers: 
    - name: nginx
      image: nginx

      env: 
      - name: POD_PSWD
        value: mySecretPassword
