# kubectl create -f deployment-def.yaml
# kubectl get deployments
# kubectl describe deployment myapp-deployment

# kubectl get all

# kubectl apply -f deployment.yml
# kubectl set image deployment/deployment.yml nginx-container=nginx:1.9.1

  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: myapp-deployment
    labels: 
      app: myapp
      tier: frontend
spec:
  template: 
    metadata: 
      name: myapp-prod
      labels: 
        app: myapp
        type: frontend
    spec:
      containers: 
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels: 
      type: frontend
