# Create                                                kubectl create -f deployment-def.yaml
# Get                                                   kubectl get deployments
#                                                       kubectl get all
#                                                       kubectl describe deployment deployment-def
# Update                                                kubectl apply -f deployment-def.yml
#                                                       kubectl set image deployment/deployment-def nginx=nginx:1.9.1
# Status                                                kubectl rollout status deployment/deployment-def
#                                                       kubectl rollout history deployment/deployment-def
# Rollback                                              kubectl rollout undo deployment/deployment-def

  apiVersion: apps/v1
  kind: Deployment
  metadata: 
    name: myapp-deployment
    labels: 
      app: myapp
      tier: frontend
spec:
  template: 
    metadata: 
      name: myapp-prod
      labels: 
        app: myapp
        type: frontend
    spec:
      containers: 
        - name: nginx-container
          image: nginx
  replicas: 3
  selector:
    matchLabels: 
      type: frontend
